--Organizational Hierarchy Explorer

CREATE TABLE EMPLOYEE (
  EmpID int,
  Ename varchar(15),
  Department varchar(10),
  ManagerID int
);

INSERT INTO EMPLOYEE VALUES (1, 'Alice', 'HR',NULL);
INSERT INTO EMPLOYEE VALUES (2, 'Bob', 'Finance',1);
INSERT INTO EMPLOYEE VALUES (3, 'Charlie', 'IT',1);
INSERT INTO EMPLOYEE VALUES (4, 'David', 'FInance',2);
INSERT INTO EMPLOYEE VALUES (5, 'Eve', 'IT',3);
INSERT INTO EMPLOYEE VALUES (6, 'Frank', 'HR',1);


--SELECT * FROM EMPLOYEE;
SELECT E.Ename AS [EMPLYEE NAME],E2.Ename AS [MANAGER NAME],
E.Department AS [EMPLOYEE DEPARTMENT],E2.DEPARTMENT AS [MANAGER DEPARTMENT]
FROM
EMPLOYEE AS E
LEFT JOIN
EMPLOYEE AS E2
ON
E.ManagerID=E2.EmpID